# Generated by Django 5.1.2 on 2024-10-28 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technichian', to='app.jobcategory')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='technician', to='app.village')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=15)),
                ('job_description', models.TextField(blank=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('technician_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='app.jobcategory')),
                ('technician_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='app.technician')),
                ('customer_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='app.village')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
