# Generated by Django 5.1.2 on 2024-11-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_job_client_name_remove_job_client_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('process', 'Process'), ('complete', 'Complete')], default='process', max_length=8),
        ),
    ]
