# Generated by Django 5.1.3 on 2024-11-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_job_created_at_alter_job_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='technician_images/'),
        ),
    ]
