# Generated by Django 5.1.3 on 2024-11-19 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
